# Auto-generated by `rake db:schema:dump`.
# Re-run after running pending migrations.

ActiveRecord::Schema.define(version: 20150522100000) do
  enable_extension "plpgsql"

  create_table "activities", force: :cascade do |t|
    t.integer  "lesson_id",      null: false
    t.string   "title",          null: false
    t.string   "kind",           default: "code", null: false
    t.text     "prompt"
    t.text     "starter_code"
    t.text     "solution"
    t.text     "spec_code"
    t.text     "choices"
    t.string   "correct_choice"
    t.integer  "position",       default: 0
    t.datetime "created_at",     null: false
    t.datetime "updated_at",     null: false
    t.text     "hints"
    t.integer  "difficulty",     default: 1
  end
  add_index "activities", ["lesson_id"], name: "index_activities_on_lesson_id"

  create_table "awards", force: :cascade do |t|
    t.integer  "user_id",     null: false
    t.integer  "badge_id",    null: false
    t.datetime "awarded_at",  null: false
  end
  add_index "awards", ["user_id", "badge_id"], unique: true

  create_table "badges", force: :cascade do |t|
    t.string   "slug",        null: false
    t.string   "name",        null: false
    t.text     "description"
    t.string   "icon_glyph",  default: "*"
    t.datetime "created_at",  null: false
    t.datetime "updated_at",  null: false
  end

  create_table "comments", force: :cascade do |t|
    t.integer  "user_id",    null: false
    t.integer  "lesson_id",  null: false
    t.text     "body",       null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "completions", force: :cascade do |t|
    t.integer  "user_id",      null: false
    t.integer  "lesson_id",    null: false
    t.datetime "completed_at", null: false
  end

  create_table "learning_modules", force: :cascade do |t|
    t.integer  "track_id",   null: false
    t.string   "name",       null: false
    t.string   "slug",       null: false
    t.text     "overview"
    t.integer  "position",   default: 0
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "lessons", force: :cascade do |t|
    t.integer  "learning_module_id", null: false
    t.string   "title",              null: false
    t.string   "slug",               null: false
    t.text     "body"
    t.integer  "position",           default: 0
    t.datetime "created_at",         null: false
    t.datetime "updated_at",         null: false
  end

  create_table "submissions", force: :cascade do |t|
    t.integer  "activity_id", null: false
    t.integer  "user_id"
    t.text     "source"
    t.string   "choice"
    t.string   "status",      default: "pending"
    t.text     "stdout"
    t.text     "stderr"
    t.float    "runtime_ms"
    t.datetime "created_at",  null: false
    t.datetime "updated_at",  null: false
  end

  create_table "tracks", force: :cascade do |t|
    t.string   "name",        null: false
    t.string   "slug",        null: false
    t.text     "description"
    t.integer  "position",    default: 0
    t.datetime "created_at",  null: false
    t.datetime "updated_at",  null: false
  end

  create_table "users", force: :cascade do |t|
    t.string   "email",              default: "", null: false
    t.string   "encrypted_password", default: "", null: false
    t.string   "nickname"
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",      default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.inet     "current_sign_in_ip"
    t.inet     "last_sign_in_ip"
    t.datetime "created_at",         null: false
    t.datetime "updated_at",         null: false
    t.boolean  "admin",              default: false, null: false
    t.integer  "current_streak",     default: 0,     null: false
    t.integer  "longest_streak",     default: 0,     null: false
    t.date     "last_activity_on"
  end
end
